project:
  type: website
  output-dir: "docs/"

website:
  title: "exemplo-blog-quarto"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: book
        href: https://www.skoob.com.br/usuario/10490743
format:
  html:
    theme: minty
    css: styles.css

editor: visual
lang: pt
